name: flutter_currency
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
  provider: ^3.0.0+1
  cupertino_icons: ^0.1.2
  rxdart: ^0.22.6
  fl_chart: ^0.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
   - assets/images/

  fonts:
      - family: Goyang-L
        fonts:
          - asset: assets/goyang_L.ttf
      - family: Goyang-R
        fonts:
          - asset: assets/goyang_R.ttf